"""
Analyse experte des colonnes à supprimer
Expert Data Science - Identification automatique des colonnes inutiles
"""

import pandas as pd
import numpy as np

print("=" * 100)
print("ANALYSE EXPERTE DES COLONNES À SUPPRIMER")
print("=" * 100)

# Charger le dataset original
df = pd.read_csv('ptbxl_database.csv', index_col='ecg_id')

print(f"\n📊 Dataset original: {len(df):,} enregistrements × {len(df.columns)} colonnes")

# Calculer les statistiques pour chaque colonne
missing_pct = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)

print("\n" + "=" * 100)
print("1. COLONNES AVEC VALEURS MANQUANTES (>0%)")
print("=" * 100)

for col, pct in missing_pct[missing_pct > 0].items():
    status = "🔴 SUPPRIMER (>95%)" if pct > 95 else "⚠️  IMPUTER (50-95%)" if pct > 50 else "✓ GÉRABLE (<50%)"
    print(f"{col:40s} : {pct:6.2f}% manquant  {status}")

# RÈGLES D'EXPERT POUR SUPPRESSION
print("\n" + "=" * 100)
print("2. DÉCISIONS EXPERTES DE SUPPRESSION")
print("=" * 100)

to_drop = []

# RÈGLE 1: Colonnes avec >95% de valeurs manquantes (inutilisables)
high_missing = missing_pct[missing_pct > 95].index.tolist()
if high_missing:
    print(f"\n✓ RÈGLE 1: Colonnes >95% vides ({len(high_missing)}) - AUCUNE VALEUR INFORMATIVE")
    for col in high_missing:
        print(f"    • {col:40s} ({missing_pct[col]:.2f}% vide)")
        to_drop.append(col)

# RÈGLE 2: Colonnes textuelles de rapport (non structurées)
text_cols = ['report', 'initial_autogenerated_report']
print(f"\n✓ RÈGLE 2: Colonnes texte rapport ({len(text_cols)}) - NON STRUCTURÉ, NLP NÉCESSAIRE")
for col in text_cols:
    if col in df.columns:
        print(f"    • {col:40s} (texte libre, nécessite NLP)")
        to_drop.append(col)

# RÈGLE 3: Colonnes redondantes (déjà encodées/extraites)
redundant = ['scp_codes', 'age_group', 'bmi_category', 'recording_date']
print(f"\n✓ RÈGLE 3: Colonnes redondantes ({len(redundant)}) - DÉJÀ ENCODÉES AILLEURS")
for col in redundant:
    if col in df.columns:
        print(f"    • {col:40s} (information déjà capturée)")
        to_drop.append(col)

# RÈGLE 4: Métadonnées de validation très incomplètes
validation_cols = ['second_opinion', 'validated_by']
print(f"\n✓ RÈGLE 4: Métadonnées validation incomplètes ({len(validation_cols)}) - >70% MANQUANT")
for col in validation_cols:
    if col in df.columns and missing_pct[col] > 70:
        print(f"    • {col:40s} ({missing_pct[col]:.2f}% vide)")
        to_drop.append(col)

# Dédupliquer
to_drop = list(set(to_drop))

print("\n" + "=" * 100)
print(f"3. LISTE FINALE DE SUPPRESSION ({len(to_drop)} COLONNES)")
print("=" * 100)
for col in sorted(to_drop):
    if col in df.columns:
        pct = missing_pct.get(col, 0)
        print(f"  • {col:40s} ({pct:6.2f}% vide)")

# Sauvegarder la liste
with open('colonnes_a_supprimer.txt', 'w', encoding='utf-8') as f:
    f.write("# Colonnes à supprimer - Décision experte\n")
    f.write(f"# Total: {len(to_drop)} colonnes\n\n")
    for col in sorted(to_drop):
        if col in df.columns:
            f.write(f"{col}\n")

print(f"\n✓ Liste sauvegardée dans: colonnes_a_supprimer.txt")

# Afficher le code Python pour le preprocessing
print("\n" + "=" * 100)
print("4. CODE PYTHON POUR PREPROCESSING")
print("=" * 100)
print("\ncolumns_to_drop = [")
for col in sorted(to_drop):
    if col in df.columns:
        print(f"    '{col}',")
print("]")

print("\n" + "=" * 100)
print(f"✓ ANALYSE TERMINÉE - {len(to_drop)} colonnes identifiées pour suppression")
print("=" * 100)
